fix: finish getting Vite 5 working
sveltejs/kit pull request #11167
Opened 2023-12-02 00:40 UTC by benmccann

https://github.com/vitejs/vite/pull/14818 broke a lot of tests. I mostly fixed it here: https://github.com/sveltejs/kit/commit/43a745ad5f516c48f08718ae256e73d9e47ef0eb.

I don't know what's causing the remaining failures, but I think it's also something related to the base path - if I remove the base path from the failing tests then they start working. You can reproduce them with:
```
cd packages/kit/test/apps/options-2
pnpm build
pnpm test:build
```

When I run `pnpm preview` in that directory everything seems to work and it looks like `started` is added to the `body`, so I don't know why the tests are failing with a timeout looking for `started`.

2023-12-02 16:30 UTC, eltigerchino commented
The tests are failing because the Vite preview middleware always returns `/` when making a request to `/basepath` or `/basepath/`. This makes it impossible to tell the difference between the two. As a result, the URL getting passed to `server.respond` is always `/basepath/` even when the browser makes a request to `/basepath` so SvelteKit can't perform a trailing slash redirect.

Essentially, the tests get stuck because it's expecting the client-side scripts to add the `started` class to the body element. But the browser can't download the scripts because the trailing slash is incorrect and our assets are linked using relative paths.

2023-12-02 16:54 UTC, eltigerchino requested changes

2023-12-02 16:54 UTC, eltigerchino commented on packages/kit/src/exports/vite/preview/index.js
> +			const resolved = new URL(base, `${protocol}://${host}`).href;
```suggestion
			req.url = req.originalUrl;
```

2023-12-02 16:54 UTC, eltigerchino commented on packages/kit/src/exports/vite/preview/index.js
> +					base: resolved.endsWith('/') ? resolved.substring(0, resolved.length - 1) : resolved,
```suggestion
					base: `${protocol}://${host}`,
```

2023-12-02 16:55 UTC, eltigerchino commented on packages/kit/src/exports/vite/preview/index.js
> +			const resolved = new URL(base, `${protocol}://${host}`).href;
```suggestion
			req.url = req.originalUrl;
			const resolved = new URL(base, `${protocol}://${host}`).href;
```

2023-12-02 23:46 UTC, eltigerchino commented on packages/kit/src/exports/vite/preview/index.js
> +			const resolved = new URL(base, `${protocol}://${host}`).href;
```suggestion

```

2023-12-02 23:48 UTC, eltigerchino commented on packages/kit/src/exports/vite/preview/index.js
> +					base: resolved.endsWith('/') ? resolved.substring(0, resolved.length - 1) : resolved,
```suggestion
					base: `${protocol}://${host}`
```

2023-12-03 00:23 UTC, benmccann commented on packages/kit/test/apps/basics/test/server.test.js
> +		// TODO: should this actually be set by default?
```suggestion
		// TODO: pass Vite's cors option to sirv. https://vitejs.dev/config/server-options.html#server-cors
```

2023-12-03 04:23 UTC, merged