chore: flesh out cloudflare bindings docs
sveltejs/kit pull request #11731
Opened 2024-01-24 17:12 UTC by Rich-Harris

stumbled on this while working on #11730

2024-01-24 18:07 UTC, ghostdevv requested changes
Unless something has changed the using the Cloudflare adapter will already install these types for you and make them globally available.

2024-01-24 18:50 UTC, Rich-Harris commented
huh, doesn't seem to be working for me. am i doing something wrong?

<img width="616" alt="image" src="https://github.com/sveltejs/kit/assets/1162160/4c8680f9-6ed0-4016-9da9-180783b82458">

2024-01-24 19:57 UTC, ghostdevv commented
> huh, doesn't seem to be working for me. am i doing something wrong?

Doesn't seem to be working for me either :thinking: @benmccann any ideas? You mentioned this to me last time

2024-01-24 22:07 UTC, benmccann commented
I'm really not the person to ask about TypeScript intricacies. Certainly if the types were available just from installing the adapter that would be nicer than if the user had to manually set things up. Perhaps @dummdidumm could provide some advice on why that might not be working

2024-01-25 06:04 UTC, eltigerchino commented
Additionally, the types are missing for the other properties declared by the adapter. `platform.cf` should be typed `IncomingRequestCfProperties`

![CleanShot 2024-01-25 at 2  02 43@2x](https://github.com/sveltejs/kit/assets/54401897/7f51e639-fc57-4ff4-ad8a-5f40a828a2bf)

2024-03-15 04:17 UTC, benmccann commented
@Rich-Harris this will need a rebase since I merged https://github.com/sveltejs/kit/pull/11732

2024-03-15 04:25 UTC, eltigerchino commented
I was using TypeScript nightly in VSCode and this wasn't an issue anymore. Maybe I'll need to check again if it was just a fluke or if it works without TypeScript nightly.

2024-03-15 12:08 UTC, eltigerchino commented
Alright. So apparently I was importing something from `drizzle/d1` in a typescript file and they've included `/// <reference types="@cloudflare/workers-types" />` in their type declaration file so the workers types became available globally.
We can do the same thing but it doesn't work when we import our adapter package in `svelte.config.js` since it's a JS file, the workers types are only available locally in that file.

So the minimum someone would need to do is add a reference to the adapter package in their `app.d.ts` and the workers types become global. They wouldn't have to install the workers types package themselves.
```diff
+ /// <reference types="@sveltejs/adapter-cloudflare" />

// See https://kit.svelte.dev/docs/types#app
// for information about these interfaces
declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}
		interface Platform {
			env: {
				example: D1Database; // we get our types!
			}
		}
	}
}

export {};
```

But it'd be even nicer if we could get rid of this step and just have the types available by including them in the generated sveltekit ambient declaration file.

2024-06-20 17:31 UTC, eltigerchino commented
Adding a note here from https://github.com/sveltejs/kit/pull/12088#issuecomment-2156091419

It was suggested to not automatically include the cloudflare types globally because they pollute the ambient types namespace.

2024-12-12 04:47 UTC, Rich-Harris commented
preview: https://svelte-dev-git-preview-kit-11731-svelte.vercel.app/

_this is an automated message_

2024-12-12 04:49 UTC, eltigerchino approved these changes
We already explicitly [import the Cloudflare types](https://svelte.dev/docs/kit/adapter-cloudflare#Runtime-APIs) in the docs. Therefore, people should know about installing the workers types package. The types can be made available globally if the user sets it up themselves. We decided not to do this automatically because it [pollutes the global ambient namespace](https://github.com/sveltejs/kit/pull/12088#pullrequestreview-2194893072)

2025-01-13 15:36 UTC, ghostdevv approved these changes

2025-01-13 15:37 UTC, merged