docs: add breakpoint debugging guide
sveltejs/kit pull request #12212
Opened 2024-05-12 12:18 UTC by theetrain

Closes #7781, relates to #1144

- Add breakpoint debugging documentation to the 'appendix' section

<img width="1209" alt="image" src="https://github.com/sveltejs/kit/assets/12798751/9338f5a4-db1c-4ba0-a78a-0444023e49d3">

While testing with the Node.js inspector, I tried to enable server-side breakpoint debugging, but was not successful. The sourcemaps are being generated, but only client-side code connect to chrome devtools. VSCode breakpoint debugging works well.

I'm hoping there could be a way to debug server-side code within chrome devtools as well, which would help developers who aren't using VSCode, but I'm unsure whose domain this falls in: SvelteKit, Vite, or something else.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [ ] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

2024-05-16 03:18 UTC, benmccann commented on documentation/docs/60-appendix/15-debugging.md
> +title: Breakpoint Debugging
I'd make this a bit more generic for the lefthand menu. I'd also move the page down an item to come after "Integrations"
```suggestion
title: Debugging
```

2024-05-16 03:23 UTC, benmccann commented on documentation/docs/60-appendix/15-debugging.md
> +			"command": "npm start",
I think it'd be helpful to make this `npm run dev` to match the text above and real projects so that the user can copy/paste this example

2024-05-16 13:05 UTC, theetrain commented
Thanks, Ben! I also added a link to Svelte Inspector for good measure.

2024-05-16 13:07 UTC, Conduitry requested changes
Proposed changes to the svelte.dev site need to target the `svelte-4` branch, not `main`.

2024-05-16 13:07 UTC, Conduitry commented
Apologies, I can't read. This is `kit`.

2024-05-23 20:51 UTC, benmccann commented on documentation/docs/60-appendix/15-debugging.md
> +			"name": "Run npm start",
```suggestion
			"name": "Run npm dev",
```

2024-05-23 20:52 UTC, benmccann commented
Can we change the page prefix from `15-` to `25-`? I'd like to keep the integrations page coming first

2024-05-23 20:53 UTC, benmccann commented on documentation/docs/60-appendix/15-debugging.md
> +With the build-in debug terminal, you can set up breakpoints in source files within VSCode.
```suggestion
With the built-in debug terminal, you can set up breakpoints in source files within VSCode.
```

2024-06-18 02:55 UTC, benmccann commented
@theetrain I think there are a couple comments outstanding on this PR. If you're able to address them I'd love to get this in. We'll be restructuring the docs and closing any open PRs, so I'd like to get it in before that happens

2024-06-19 02:01 UTC, merged

2025-09-04 12:13 UTC, fbruckhoff commented
Please note that server-side debugging is (no longer) possible in VSCode due to source map issues. Breakpoints won't bind. The documentation needs to address source map configuration thoroughly.