fix: @sveltejs/enhanced-img broken behavior on client navigation
sveltejs/kit pull request #12551
Opened 2024-08-06 11:35 UTC by Winne4r

This small fix was crucial because, without it, the package was unusable. The original behavior caused the src attributes of images to be replaced with "import.meta.url" + ... on any client navigation.

By adding escaping brackets, the package now functions as expected.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

2024-08-06 15:03 UTC, benmccann approved these changes
thanks!! i'm not sure how this was overlooked for so long. I really appreciate you finding and fixing it!

2024-08-06 16:15 UTC, eltigerchino commented
Some of the tests seem to be failing because the src ends up with double curly brackets such as `<img src={{image.img.src}}`. I'm not sure what's the reason for it though.

2024-08-06 17:35 UTC, Conduitry requested changes
We need to figure out what's going on here with the double braces. The preprocessor is producing code that is not syntactically valid.

2024-08-06 17:54 UTC, benmccann requested changes
If possible, I'd also like to avoid braces in cases like `src={"/7"}` since they're unnecessary and just result in larger and slower code

@Winne4r can you provide a reproduction of the bug you were facing?

2024-08-06 18:16 UTC, Winne4r commented
`<enhanced:img src="$lib/images/svelte-welcome.png" alt="An alt text" />`

leads to:
![image](https://github.com/user-attachments/assets/857124db-0b8d-45d0-9d08-fee1aa05ff32)

src on img totally broken
(production mode only)

2024-08-07 04:11 UTC, benmccann commented
fixed here: https://github.com/sveltejs/kit/commit/65931f276ac2102032e3032c864a472eee19b7bb

2024-08-07 04:11 UTC, closed without merging