Added option to sveltekit vite project to adjust root
sveltejs/kit pull request #13027
Opened 2024-11-19 18:06 UTC by cromefire

Properly fixes #12499 (or at least hotfixes it).

Just provides an option to change the root as svelte ignores vite's root setting...

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

2024-11-19 18:07 UTC, Rich-Harris commented
preview: https://svelte-dev-git-preview-kit-13027-svelte.vercel.app/

_this is an automated message_

2024-11-19 22:25 UTC, benmccann requested changes
It seems from https://github.com/sveltejs/kit/issues/12499#issuecomment-2486397815 that you're arguing we should respect the options in the Vite config. But if that's so, then I would expect `root` to be read from the Vite config (https://vite.dev/config/shared-options.html#root) instead of specified in a new location. It's already hard enough that we have a Svelte config and Vite config. I don't particularly want to add a third location to specify configuration options

2024-11-20 00:20 UTC, cromefire commented
I mean yeah, ideally, but it's beyond my capabilities to get that working, so this is at least something simple that does work... If you are capable of properly fixing it, it'd definitely be better.

2024-11-20 00:41 UTC, benmccann commented
Well there's 745 open issues, so it's not likely I'll get to that particular one

But I'm afraid I'm going to have to close this given the approach

2024-11-20 00:41 UTC, closed without merging

2024-11-20 00:47 UTC, cromefire commented
Doesn't really help (the already pretty terrible) dev experience when getting an actual production application to properly work... Gotta say the more I use it it seems that svelte is really just designed to be used as a demo framework to get a prototype onto vercel, once you go only slightly off that path it seems nobody actually tested anything...

2024-11-20 08:44 UTC, DannyvanHolten commented
Hey @benmccann. Is there any direction you are thinking of? I don't know If I can be of direct help, but I'm willing to put in some hours in December, to get to know how this works.