feat: validate values for `cache-control` and `content-type` headers in dev mode
sveltejs/kit pull request #13114
Opened 2024-12-06 15:34 UTC by JR-G

Fix for [#12784](https://github.com/sveltejs/kit/issues/12784)

Adds validation for common HTTP headers in dev mode to help catch invalid values early:
- Validates cache-control directives against standard values
- Validates content-type format
- Only active in dev mode

run `pnpm dev` from `test/apps/basics` and navigate to [http://localhost:5173/headers/invalid](http://localhost:5173/headers/invalid). In your console you'll see:
```
[SvelteKit] Invalid cache-control directive "totally-invalid". Did you mean one of: max-age, public, private, no-cache, no-store, must-revalidate, proxy-revalidate, s-maxage, immutable, stale-while-revalidate, stale-if-error, no-transform, only-if-cached, max-stale, min-fresh
[SvelteKit] Invalid content-type value "not-a-real-type"
```

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

2024-12-06 15:35 UTC, Rich-Harris commented
preview: https://svelte-dev-git-preview-kit-13114-svelte.vercel.app/

_this is an automated message_

2024-12-06 20:43 UTC, benmccann commented on .changeset/rich-pants-beam.md
> +in dev mode to help catch invalid values early.
```suggestion
feat: validate values for `cache-control` and `content-type` headers in dev mode
```

2025-01-15 21:40 UTC, elliott-with-the-longest-name-on-github requested changes

2025-01-15 21:40 UTC, elliott-with-the-longest-name-on-github commented on packages/kit/src/runtime/server/validate-headers.js
> +			.map((directive) => directive.trim().split('=')[0].toLowerCase());
```suggestion
			.map((directive) => directive.trim().split('=').at(0)?.toLowerCase());
```

Is it possible for the string to end up with an empty entry after splitting on `','`? Like `cache-control: stale-while-revalidate,,no-transform` or something? Obviously that's still wrong, but hopefully we'd catch that and show an error, not throw a hard-to-debug runtime error :thinking:

2025-01-15 21:40 UTC, elliott-with-the-longest-name-on-github commented on packages/kit/src/runtime/server/validate-headers.js
> +	}
```suggestion
			try {
				validator?.(value);
			} catch (error) {
				if (error instanceof Error) {
					console.warn(`[SvelteKit] ${error.message}`);
				}
			}
		}
```

Saves an extra level of indentation?

2025-01-15 21:40 UTC, elliott-with-the-longest-name-on-github commented on packages/kit/src/runtime/server/validate-headers.spec.js
> +		// @ts-expect-error
Same thing here, I think you can add a global declaration to the top and avoid using `globalThis` here.

2025-01-15 21:40 UTC, elliott-with-the-longest-name-on-github commented on packages/kit/src/runtime/server/validate-headers.js
> +const CONTENT_TYPE_PATTERN = /^[a-z]+\/[-+.\w]+$/i;
This won't work as-is: `Content-Type` isn't just `type/subtype`, it's `type/subtype[;parameter=value]` -- for example, `Content-Type: text/html; charset=UTF-8`. There are other parameters that you can provide as well. We could opt out of checking these for validity by splitting the value on `;` and only taking the first part? I'm not sure the spec is specific enough on the parameters to make validation useful.

2025-01-22 22:54 UTC, elliott-with-the-longest-name-on-github commented on packages/kit/src/runtime/server/validate-headers.js
> +	/^(application|audio|font|image|model|text|video|x-[a-z]+)\/[-+.\w]+$/i;
```suggestion
	/^(application|audio|font|image|model|text|video|x-[a-z]+)\/[-+.\w]+$/i;
```

[The IANA spec](https://www.iana.org/assignments/media-types/media-types.xhtml) defines the following top-level types, some of which are not included here:
- [application](https://www.iana.org/assignments/media-types/media-types.xhtml#application)
- [audio](https://www.iana.org/assignments/media-types/media-types.xhtml#audio)
- [example](https://www.iana.org/assignments/media-types/media-types.xhtml#example)
- [font](https://www.iana.org/assignments/media-types/media-types.xhtml#font)
- [haptics](https://www.iana.org/assignments/media-types/media-types.xhtml#haptics)
- [image](https://www.iana.org/assignments/media-types/media-types.xhtml#image)
- [message](https://www.iana.org/assignments/media-types/media-types.xhtml#message)
- [model](https://www.iana.org/assignments/media-types/media-types.xhtml#model)
- [multipart](https://www.iana.org/assignments/media-types/media-types.xhtml#multipart)
- [text](https://www.iana.org/assignments/media-types/media-types.xhtml#text)
- [video](https://www.iana.org/assignments/media-types/media-types.xhtml#video)

2025-01-22 22:54 UTC, elliott-with-the-longest-name-on-github commented on packages/kit/test/apps/basics/src/routes/headers/invalid/+server.js
You can move this to the `test-dev-only` package -- that package only runs dev tests, which means you don't need to fake the `globalThis.__SVELTEKIT_DEV__` thing.

2025-01-24 14:04 UTC, JR-G commented on packages/kit/src/runtime/server/validate-headers.js
> +			.map((directive) => directive.trim().split('=')[0].toLowerCase());
This was a good point! I've introduced an additional check to catch the empty directives.

2025-01-24 14:05 UTC, JR-G commented on packages/kit/src/runtime/server/validate-headers.spec.js
> +		// @ts-expect-error
I found success in the other declarations, but I didn't have much luck silencing it here, despite trying a couple of things 🤔.

2025-01-24 14:05 UTC, JR-G commented on packages/kit/src/runtime/server/validate-headers.js
> +	/^(application|audio|font|image|model|text|video|x-[a-z]+)\/[-+.\w]+$/i;
Thanks! Updated to reflect this.

2025-01-24 14:05 UTC, JR-G commented on packages/kit/test/apps/basics/src/routes/headers/invalid/+server.js
Shifted!

2025-01-29 20:05 UTC, elliott-with-the-longest-name-on-github commented
Thanks @JR-G! I pushed a commit with a few improvements to the tests (mainly just simplifying setup) and some additional information in the error messages. Great PR. Merging as soon as CI passes :)

2025-01-29 20:33 UTC, elliott-with-the-longest-name-on-github approved these changes

2025-01-29 21:51 UTC, merged