[breaking] update prerender options for providing list of pages
sveltejs/kit pull request #2291
Opened 2021-08-25 15:46 UTC by benmccann

Closes https://github.com/sveltejs/kit/issues/2185

The main reason for this is to clarify the options. It was confusing to people that `pages` wasn't just a list of pages to prerender and that the option behaved differently depending on whether `crawl` was `true` or `false`

This also happens to be more powerful because you can specify some pages to crawl and some pages to pre-render without crawling, which you could not do before

For users that had set `pages` with `crawl: true` they will need to move that option value to `crawl`

2021-09-02 17:54 UTC, dreitzner requested changes
As soon as the tests are fixed/extended this should be fine. 👏

2021-09-06 15:01 UTC, Rich-Harris commented
I don't understand this PR at all! `pages` and `crawl` are both treated identically here, no?

```js
if (config.kit.prerender.enabled) {
	if (config.kit.prerender.crawl) {
		visit_pages(config.kit.prerender.crawl);
	}
	visit_pages(config.kit.prerender.pages);
}
```

Even if that's unintentional, we're still left with a situation where `crawl` and `pages` have confusingly similar meanings. I'm open to changing things if people are confused (perhaps `pages` becomes `entries`?) but this doesn't seem like the right fix to me.

2021-09-06 15:57 UTC, benmccann commented
No, `pages` and `crawl` are not identical (unless I made a mistake somewhere). `pages` only pre-renders that exact list of pages and none of the linked pages whereas `crawl` will crawl all of the pages discoverable by links. Does it make any more sense to you now given that explanation?

2021-09-06 16:03 UTC, Rich-Harris commented
I'm afraid not, no. As far as I can see, `pages` and `crawl` are treated identically in this PR?

2021-09-06 16:29 UTC, benmccann commented
Oops. Yeah. I've fixed it so that it should behave the way I described now (I hope. I'm on my phone, so not ideal for code editing. It looks like it needs a rebase, so I can do that later today)

2021-09-06 20:37 UTC, Rich-Harris commented
Gotcha. I'm still pretty confused about why we'd want to do this — I can't really think of a situation where you'd want to crawl some pages but not _these specific pages_, which you still want to prerender. This PR wouldn't solve the problem swyx encountered in #1683, which was that he didn't understand that `pages` was a set of entry points for the crawler and that he'd still need to slap `prerender = true` on those pages unless he was using adapter-static.

I really think we should just rename `prerender.pages` to `prerender.entries` and keep `crawl` as it is.

2021-09-06 21:24 UTC, closed without merging