[docs] add docs for vite-plugin-svelte
sveltejs/kit pull request #2665
Opened 2021-10-22 17:37 UTC by Mlocik97

### Before submitting the PR, please make sure you do the following
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2021-11-01 17:18 UTC, bluwy commented on documentation/docs/14-configuration.md
> +const vitePluginSvelteConfig = {};
Having an object, and then spreading feels odd to me. Currently, top-level properties like `preprocess` and `compilerOptions` are used by `vite-plugin-svelte` too, so the separation may be a bit misleading. I think we should remove this line and the spreading expression below, and then...

2021-11-01 17:18 UTC, bluwy commented on documentation/docs/14-configuration.md
>  	preprocess: null
... After the end of this code block, we can add a short blockquote like:

> Note that the root scope of the config also applies to [vite-plugin-svelte](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md)

2021-11-01 17:18 UTC, bluwy commented on documentation/docs/14-configuration.md
> +A [vite-plugin-svelte config object](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md). These options must be in root scope of config object in svelte.config.js file.
This also feels a bit out of place. The list of options here implies `config.kit.*` but this section is for the spread expression only. I think we can remove this too with the suggestion above.

2021-11-02 10:24 UTC, ignatiusmb requested changes
This PR is getting too involved for such a straightforward change, we don't want to overwhelm newcomers by having too much information in the face when reading through the docs.

A comment on the config example explaining that options from the plugin can also be passed should be enough, maybe update docs on plugin repo to have an example usage with SK if needed, I left a suggestion to that comment, I'll leave the plugin docs to @dominikg and @bluwy

2021-11-02 10:24 UTC, ignatiusmb commented on documentation/docs/14-configuration.md
> +	...vitePluginSvelteConfig,
```suggestion
	// SvelteKit uses vite-plugin-svelte, plugin options can be passed through here
	// see available options (https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md)
```

2021-11-02 11:49 UTC, dominikg approved these changes

2021-11-02 11:59 UTC, ignatiusmb approved these changes

2021-11-02 13:07 UTC, bluwy approved these changes

2021-11-02 15:47 UTC, benmccann commented on documentation/docs/14-configuration.md
> +	// SvelteKit uses vite-plugin-svelte, plugin options can be passed through here
```suggestion
	// SvelteKit uses vite-plugin-svelte. Plugin options can be provided directly here.
```

2021-11-02 15:48 UTC, benmccann commented on documentation/docs/14-configuration.md
> +	// SvelteKit uses vite-plugin-svelte. Plugin options can be provided directly here.
```suggestion
	// SvelteKit uses vite-plugin-svelte. Its options can be provided directly here.
```

2021-11-02 15:48 UTC, benmccann commented on documentation/docs/14-configuration.md
> +	// see available options (https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md)
```suggestion
	// See the available options at https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md
```

2021-11-02 15:49 UTC, merged