adapter-cloudflare: use system path delimiter
sveltejs/kit pull request #2950
Opened 2021-11-30 03:07 UTC by piperswe

On Windows, the paths in `ASSETS` use backslashes instead of slashes, so they'll never match a request. This patch replaces whatever the platform-specific separator is with a regular slash.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2021-11-30 16:31 UTC, piperswe commented
I am now realizing that this isn't as useful as I was thinking since Cloudflare Pages builds sites itself on Linux.

2021-12-01 00:48 UTC, benmccann commented
> I am now realizing that this isn't as useful as I was thinking since Cloudflare Pages builds sites itself on Linux.

Is this something you still want to pursue then? Is it useful for testing and debugging locally on Windows?

2021-12-01 06:42 UTC, piperswe commented
> > I am now realizing that this isn't as useful as I was thinking since Cloudflare Pages builds sites itself on Linux.
> 
> Is this something you still want to pursue then? Is it useful for testing and debugging locally on Windows?

It could be - this patch works fine and barely adds any complexity, so it's probably worth it to merge.

2021-12-01 13:38 UTC, lukeed requested changes

2021-12-01 13:38 UTC, lukeed commented on packages/adapter-cloudflare/index.js
> +			const static_assets = [...static_files, ...client_files].map((f) => f.replaceAll(sep, '/'));
This requires Node 15, which is higher than SvelteKit's 14 minimum. Best to use a RegExp, `/[\\\/]+/g`

2021-12-01 13:39 UTC, lukeed commented
As mentioned, this is optional. Not necessary cuz Pages is always built on Linux

2021-12-01 14:44 UTC, Conduitry reviewed
I'm personally against this added complexity, since the build will always be run on Linux anyway. As Luke noted in his comment, even innocuous changes like this one can inadvertently introduce new dependencies (like that on Node 15). There's no reason to make this more flexible than it needs to be.

2021-12-01 18:29 UTC, lukeed commented
+1, in favor of closing

2021-12-01 18:31 UTC, pngwn commented
May need to revisit if we start running adapters in dev but we should wait until we have a problem before we solve it. 

Also don't think we should add unnecessary complexity for no reason, however small.

2021-12-01 18:41 UTC, closed without merging