Exclude routes
sveltejs/kit pull request #3576
Opened 2022-01-27 20:39 UTC by Rich-Harris

For some reason the `gh pr checkout 2932` workflow failed — I can't push to the branch in #2932 — so I've created this branch to continue work on it. Thanks to @tony19 for making this happen. 

For simplicity, and consistency with the `kit.package.files`, `kit.package.exports` and `kit.serviceWorker.files` options, we should only allow a function, rather than an array of strings and regexes and functions. The question is whether to make it a `(filepath: string) => boolean` function, or keep the `basename` argument and either a) introduce inconsistency, or b) impose a breaking change on those other options.

The breaking change would be unfortunate because at the moment it's very easy to use with globbing libraries...

```js
import mm from 'micromatch';

export default {
  kit: {
    package: {
      files: mm.matcher('!**/build.*')
    }
  }
};
```

...so I'm inclined to go with `(filepath: string) => boolean`, since it's trivial to derive the basename.

I also think `kit.excludes` is probably a bit too mysterious. Perhaps `kit.routes` (or `kit.routing.include`, though we don't currently have anything else to go under `routing`) would be better, though at that point we'd have `kit.routes` and `kit.router`, which makes me want to put `kit.router` and `kit.hydrate` under `kit.browser` or something.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2022-01-27 21:18 UTC, dreitzner requested changes

2022-01-27 21:18 UTC, dreitzner commented on documentation/docs/14-configuration.md
> +**Default:** `[/^[_.]/]` *(exclude files that begin with `_` or `.`)*
Does not match pattern in line 36

2022-01-28 01:55 UTC, ignatiusmb approved these changes

2022-01-28 20:57 UTC, merged

2023-04-29 11:06 UTC, autr commented
Whatever happened to this? None of these options seem available in V1 releases.

https://github.com/sveltejs/kit/issues/2930