[fix] page.url.searchParams not set on first page land with static build #3650
sveltejs/kit pull request #3680
Opened 2022-02-02 05:42 UTC by aolose

fix #3650 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2022-02-02 14:51 UTC, dreitzner requested changes

2022-02-02 14:51 UTC, dreitzner commented on packages/kit/src/runtime/client/start.js
> +		hydrate.url.search = url.search;
Should this not be the same as
```
hydrate.url.search = location.search
```

2022-02-02 15:35 UTC, aolose commented on packages/kit/src/runtime/client/start.js
> +		hydrate.url.search = url.search;
It's same.  :smiley:

2022-02-15 23:18 UTC, Rich-Harris commented
Thank you — closing in favour of #3942, which has the same effect as far as search params go, but replaces the entire URL instead

2022-02-15 23:18 UTC, closed without merging