never allow trailing slash for endpoints
sveltejs/kit pull request #4699
Opened 2022-04-22 19:27 UTC by Rich-Harris

#2796. Right now, the `trailingSlash` option applies to all paths. Now that we've got rid of fallthrough routes, and can match pathnames to routes immediately, we have the option of only applying the `trailingSlash` option to pages. I think we should take it.

This is a breaking change. An alternative would be to add a new option, like

```js
trailingSlash: { pages: 'always', endpoints: 'never' }
```

or something, but I think that'd be a mistake. Right now, `always` _really_ means 'always unless the last segment of the path includes a `.` character' (i.e. `/foo.json` never redirects to `/foo.json/`), which is really just a proxy for 'always unless it's an endpoint', except that it has both false positives and negatives.

There's some redirect logic in `adapter-vercel` that I think we'd need to get rid of as well (it applies similar logic to what we currently have, but at the router layer rather than the application layer, and I think it's unnecessary). I think that's the only adapter that would need changing.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2022-04-23 21:13 UTC, Conduitry commented
As I mentioned on Discord, I think `ignore` as the forced behavior for endpoints would make more sense than `never`. I don't feel extremely strongly about this, however.

2022-04-23 21:18 UTC, Conduitry commented
Having it be `ignore` would also give people the option to look at `event.url` and manually redirect in their endpoint if they're doing something unusual like serving HTML from there and want to have some say about the trailing slash. I feel a bit more strongly about this now than I did before.

2022-04-25 20:51 UTC, Conduitry requested changes
PR title and changeset should be updated, but otherwise this looks good to me.

2022-04-25 22:07 UTC, Rich-Harris commented on .changeset/tender-geckos-agree.md
> +Never allow trailing slash for endpoints
```suggestion
Ignore `trailingSlash` for endpoint requests, apply `trailingSlash` to pages consistently
```

2022-04-25 22:08 UTC, Conduitry approved these changes

2022-04-25 22:09 UTC, merged