feat: Moved `ResolveOptions` and `RequestEvent` to public (closes #4805)
sveltejs/kit pull request #4809
Opened 2022-05-03 21:21 UTC by tcc-sejohnson

#4805 only explicitly requested moving `RequestEvent` to `index.d.ts`, but `ResolveOptions` is also part of `Handle`'s input API, so I moved it too. If, for some reason, we don't want that to be a publicly-accessible type, I'll move it back.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2022-05-04 15:06 UTC, carusog approved these changes

2022-05-12 06:05 UTC, ignatiusmb requested changes
Please sort the changes alphabetically

2022-05-15 00:50 UTC, tcc-sejohnson commented
@ignatiusmb 

Sorry about that! Been on vacation. Didn't even think to check for sorting -- I figured that was something the linter handled. Done!

2022-05-16 07:55 UTC, ignatiusmb approved these changes
Thanks!

2022-05-17 10:43 UTC, dummdidumm approved these changes

2022-05-18 11:26 UTC, merged

2022-05-18 11:26 UTC, Rich-Harris commented
thank you!