remove `compression` middleware from adapter-node output server
sveltejs/kit pull request #5506
Opened 2022-07-13 18:18 UTC by Rich-Harris

This is an alternative to #5491. Adding a new option that adds or disables the middleware feels like a bad precedent, and we've often wondered if it really belongs here (rather than at the load balancer level, for example).

Since we clearly document how to use the exported handler with a custom server, I think it's safe to err on the side of simplicity and just get rid of it

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2022-07-13 18:22 UTC, benmccann requested changes
I much prefer the original PR https://github.com/sveltejs/kit/pull/5491. If we want to avoid the option, maybe we could merge this PR and then revert it after `compression` is fixed?

2022-07-13 18:26 UTC, Rich-Harris commented
Adding options for this sort of thing is just (sorry) bad API design. It's out of place, and having it be a boolean value assumes that we know best what options to set for `threshold`, `level` etc. It was a mistake to ever add the middleware

2022-07-13 18:32 UTC, benmccann commented
Sure, but it doesn't have to be a boolean. We can pass through the compression options by making it a build time option instead of runtime option

2022-07-14 19:33 UTC, merged

2022-07-14 19:33 UTC, Rich-Harris commented
We decided to go ahead with this for now, just so we have a working version. Whether and how we reinstate it is still up for debate

2022-07-19 23:30 UTC, coryvirok commented
Sad panda on this one. Anyone have a viable alternative to `compression` to use? I've tried creating a Vite plugin using `compression` but have run into the same hanging issue that this PR addresses.

 Also, does anyone know why this only started happening with the Vite 3 release?

2022-07-19 23:34 UTC, benmccann commented
It's not related to Vite 3, but because SvelteKit started streaming recently and compression's streaming implementation is broken. We're waiting for the fix: https://github.com/expressjs/compression/pull/183

2022-07-22 18:32 UTC, itssumitrai commented
Is there some alternative which could be applied in mean time to prevent the node hanging issue ? Most of us who use Sveltekit on production environment are currently completely blocked with the streaming & compression change. We have to keep Kit pinned at `1.0.0-next.378`

2022-07-22 18:36 UTC, benmccann commented
Compression has been removed, so if you update to the latest it will work. You can do compression in your load balancer or a hook if you need. We can consider adding compression back after it's been fixed

2022-07-22 19:58 UTC, coryvirok commented
If someone can figure out a way to implement that hook, I'd be interested. It's pretty crazy how many of the frameworks use the `compression` module and just how long it's been broken for. 

I host on Google Cloud Run which doesn't have an option to add compression so my users are sort of stuck with large payloads till there's a workaround.

2022-07-23 11:47 UTC, fernandolguevara commented
@coryvirok an alternative could be to wrap the sveltekit handler (generated by the adapter) with a custom server implementation and in this server u need to enable the comoression middleware.

2022-08-10 15:06 UTC, lkj4 commented
Since I've upgraded to `next.405` I get following on `pnpm run build`. Is this related to this thread? Can't find the cause and don't know where to look (fwiw, I have a `vite.config.js` and `pnpm run dev` is working flawlessly).

```
failed to load config from /home/[...]/vite.config.js
error during build:
TypeError: Class extends value undefined is not a constructor or null
    at file:///home/[...]/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.405_svelte@3.48.0+vite@3.0.5/node_modules/@sveltejs/kit/dist/node/polyfills.js:17900:25
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async loadConfigFromBundledFile (file:///home/[...]/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:62986:21)
    at async loadConfigFromFile (file:///home/[...]/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:62872:28)
    at async resolveConfig (file:///home/[...]/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:62486:28)
    at async doBuild (file:///home/[...]/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:43414:20)
    at async build (file:///home/[...]/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:43403:16)
    at async CAC.<anonymous> (file:///home/[...]/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/cli.js:747:9)
 ELIFECYCLE  Command failed with exit code 1.
```