[chore] update test apps to Vite 3.0.5
sveltejs/kit pull request #5861
Opened 2022-08-10 00:03 UTC by benmccann

2022-08-15 22:28 UTC, Rich-Harris approved these changes

2022-08-15 22:29 UTC, Rich-Harris approved these changes

2022-08-16 12:57 UTC, Conduitry requested changes
Vite 3.0.8 has been released now.

2022-08-16 16:13 UTC, Rich-Harris commented
The reason the tests are failing is that [index.js](https://github.com/sveltejs/kit/blob/master/packages/kit/src/index/index.js) and [private.js](https://github.com/sveltejs/kit/blob/master/packages/kit/src/index/private.js) are now being imported twice, breaking the `instanceof` check. I'm not sure what changed in Vite to break this

2022-08-16 16:26 UTC, Rich-Harris commented
It works with `3.0.2` and below, fails with `3.0.3` and above. Of the [changelog entries](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#303-2022-07-25), the following commits look most suspicious:

* https://github.com/vitejs/vite/commit/d420f01
* https://github.com/vitejs/vite/commit/ea27701
* https://github.com/vitejs/vite/commit/c33e365

2022-08-16 16:32 UTC, Rich-Harris commented
It appears to only be a problem when the `@sveltejs/kit` package is linked — i.e. it's affecting our tests, and any projects that have something like this...

```json
{
  "pnpm": {
    "overrides": {
      "@sveltejs/kit": "../kit/packages/kit",
```

...but not normal apps

2022-08-17 16:46 UTC, benmccann commented on .changeset/pink-gorillas-watch.md
> +[chore] upgrade to Vite 3.0.8
```suggestion
[chore] upgrade to Vite 3.0.8 and esbuild 0.14.54
```

2022-08-17 22:49 UTC, Rich-Harris approved these changes

2022-08-17 23:18 UTC, Conduitry approved these changes

2022-08-17 23:35 UTC, merged