[marketing] homepage updates
sveltejs/kit pull request #5869
Opened 2022-08-11 05:05 UTC by benmccann

Just throwing something up to facilitate high-level discussion. Not ready for review

Resurrection of the work I started last year in https://github.com/sveltejs/sites/pull/72
Incorporating Figma design from @vedam: https://www.figma.com/file/f87psJnCeqMbUPAQABmCrN/svelte?node-id=0%3A1

2022-08-12 12:30 UTC, martinbeentjes commented
Oh that's a very neat looking improvement!

2022-08-13 08:30 UTC, kevmodrome commented
This is a great addition to the website! Good work!

2022-08-16 19:23 UTC, Conduitry requested changes
We made this mistake with the Svelte repo and I _really_ don't want to repeat it with the Kit repo. Making everyone who clones this repo download a 50MB video file is bad. We have https://github.com/sveltejs/assets (which is served via GitHub pages) for precisely this.

2022-08-16 21:12 UTC, benmccann commented
Yeah, my plan was to put the video elsewhere once the content is finalized. I just put it here temporarily for ease of development and sharing

2022-08-19 13:08 UTC, benzara-tahar commented
I like the changes, I know it's a not related to this PR but is there a plan to add some dope dark theme support for the official website and documentation? I'm sure that will have great unsubconsious positive impact , especially for new developers

2022-08-19 13:34 UTC, benmccann commented
No plans at the moment. I like dark theme, but it's a big change to make sure all of our assets display well on light and dark

2022-12-08 19:02 UTC, Rich-Harris commented
closing as the homepage has been updated

2022-12-08 19:02 UTC, closed without merging