start to remove app utils
sveltejs/kit pull request #600
Opened 2021-03-23 18:13 UTC by antony

Relates to https://github.com/sveltejs/kit/issues/592

A work in progress, we still need to consider that `mkdirp` is used by esm and cjs importers, so it may need to be compiled within kit and exposed.

2021-03-23 23:50 UTC, Rich-Harris requested changes
LGTM. this feels much nicer to me. mind running `pnpx changeset` before we merge?

2021-03-23 23:56 UTC, antony commented
Wasn't sure what our versioning strategy was so I went with `patch` as per other changsets.

2021-03-24 00:04 UTC, Rich-Harris approved these changes

2021-03-24 00:04 UTC, merged

2021-03-24 00:04 UTC, Rich-Harris commented
yeah, i've been doing `patch`. will have to figure out how to break that muscle memory when we leave prerelease mode

2021-03-24 03:50 UTC, benmccann commented on packages/adapter-vercel/index.js
> +			builder.copy(join(__dirname, 'files'), lambda_directory);
I don't see any method called `copy` on the `Builder`

We really need to introduce type checking everywhere