OPTIONS http method Added
sveltejs/kit pull request #6030
Opened 2022-08-18 11:34 UTC by amunim

Fixed #5193

Formatted using `pnpm format`

- [ issue #5193 ] 
- [ server.test.js has a test] Ideally, include a test that fails without this PR but passes with it.
- [I ran the tests] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`
- [no such changes ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2022-08-18 11:59 UTC, dummdidumm commented
Thank you! I'd like to hold off on merging this until we decided what to do with the form proposal, which likely changes what's allowed inside `+page.server.js`.

2022-08-18 14:05 UTC, benmccann requested changes
Your new test seems to be failing:
>@sveltejs/kit:test:   1 failed
@sveltejs/kit:test:     [chromium-dev-no-js] › test/server.test.js:52:2 › Endpoints › OPTIONS request ==================

2022-08-19 02:45 UTC, rmunn commented
Nice work so far. As this seems to be your first contribution, I'd like to give a small pointer on the use of the PR template: those `[ ]` boxes are Markdown code for checkboxes, and you can put a check in them by writing `[x]` (convert the space to an x — I've seen `[ x]` and `[x ]` a lot, which won't work, it has to be `[x]`). What you've written in the PR description is fine, it's perfectly understandable, it's just not quite how the template was intended to be filled out. :-)

2022-09-13 23:59 UTC, benmccann commented
@amunim this PR would need to be rebased and the failing tests would need to be fixed

2022-09-18 08:20 UTC, amunim commented
I am so confused at this point, I have literally searched the whole project and replaced all 204s with 555, 553, and 554 respectively but am still getting 204 as result in my tests.

2022-09-21 04:26 UTC, amunim commented
I'll rebase and work on another issue for now...

2022-09-21 04:26 UTC, closed without merging