[breaking] add embedded option, turned off by default
sveltejs/kit pull request #7969
Opened 2022-12-06 15:05 UTC by dummdidumm

## Migration

If you relied on the new behavior introduced in #7766, you can get that back by adding `embed: true` to your `svelte.config.js`:

```diff
export default {
  kit: {
+    embed: true
  }
}
```

## PR description

Closes #7940
Adds a new option which defaults to false. If true, events related to navigation etc are listened to on the target element rather the html root

Open questions:
- approach sensible? I figured using the `define` feature for this is the most straightforward and treeshakes nicely
- using `data-sveltekit-root` instead (as discussed in the issue)? Advantage: no config option, more control ("I use popper.js with embedded Kit, and it adds itself to some tag higher than the target). Disadvantage: feels clunky, a little more startup code that might not be as reliable.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2022-12-06 15:36 UTC, arackaf commented
🎉🥳🎊🍾

2022-12-08 22:49 UTC, benmccann requested changes
we need a docs change still for this one

2022-12-08 23:12 UTC, Rich-Harris approved these changes

2022-12-08 23:15 UTC, Rich-Harris commented
I'm not sure how best to add docs for this beyond https://kit-svelte-e9gz8bfaa-svelte.vercel.app/docs/configuration#embedded? (Though I guess it should probably mention the `params` stuff. Oh, and we can skip sending `params` from the server unless `embedded: true`. Will update in a sec)

<img width="856" alt="image" src="https://user-images.githubusercontent.com/1162160/206586538-52c74d53-c74f-487a-bbf6-239a61c631c5.png">

This is a niche enough thing that it probably doesn't warrant a new section of the docs — I think it's probably enough that people can find it via the config docs, and we can point people to it as and when needs arise.

2022-12-08 23:21 UTC, Conduitry commented
I'm in favor of not documenting this further than this note in the configuration docs, especially since the old default behavior was (it would seem) solely for the benefit of the NY Times and I'm sure they have other out-of-band ways of complaining to you.

2022-12-08 23:29 UTC, arackaf commented
Should we investigate which irresponsible individual at the NYT was shipping things to production using a pre-beta application framework?

2022-12-09 00:52 UTC, merged

2022-12-12 23:15 UTC, johnnysprinkles commented
Awesome, I just got SvelteKit 1.0.0-next.584 and can confirm #4935 is resolved. By the way, this is for a SvelteKit app related to the recently announced Apple Music Sing feature.

2023-12-12 20:33 UTC, patriciatiffany commented
I came here from the docs, trying to figure out what `embedded: true` does, exactly. I have an inkling it will be useful for my use cases, but that short phrase in the docs isn't quite enough for me to understand. Could I get some context?