error in dev mode if global fetch is used with relative URL
sveltejs/kit pull request #8370
Opened 2023-01-06 16:39 UTC by Rich-Harris

closes #7976

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

2023-01-08 13:10 UTC, Conduitry requested changes
What happens if someone uses a protocol-relative URL like `//foo/bar`? This check would fail to catch it and it would (I think) then still fail with the global `fetch`.

Can we instead just check something simpler like that the URL matches `/^\w+:\/\//`? Or heck, just hard code `http://` and `https://` since I don't think anything else would succeed anyway?

2023-01-08 17:17 UTC, Rich-Harris commented on packages/kit/src/exports/vite/dev/index.js
> +		}
probably simpler

```suggestion
		if (typeof info === 'string' && !/^\w+:\/\//.test(info)) {
			throw new Error(
				`Cannot use relative URL (${info}) with global fetch — use \`event.fetch\` instead: https://kit.svelte.dev/docs/web-standards#fetch-apis`
			);
		}
```

2023-01-08 17:17 UTC, Rich-Harris commented
The check would work — `new URL('//foo.com', 'fake://fake').protocol === 'fake:'`. But yeah, a regex is probably simpler. I opened a suggestion

2023-01-08 19:01 UTC, Conduitry commented
Oh, whoops, not sure what I was thinking there anymore. I do still like the regex though.

2023-01-09 09:38 UTC, dummdidumm approved these changes
Approving the regex approach. Hardcoding http(s) would make things like tauri apps etc impossible to use the global fetch

2023-01-09 15:31 UTC, merged